### ISSUE TITLE
Map Not showing, Help

### ISSUE THREAD

**Issue by Dimitri21** [bradcornford/Googlmapper#229]
The map didn't showing, here's my code 

Controller
```
public function index(){
        Mapper::map(-0.944080, 100.354655);
        
        return view('index');
      
    }
```

View
```
<div style="width: 100%; height: 100%;">
	{!! Mapper::render() !!}
</div>
```

In console it's showing a warning :

Google Maps API warning: SignedInNotSupported https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported
NC.j @ util.js:249

**Comment by bradcornford** [comment]
Hi there,

For some reason, GoogleMaps wont load in a relative height div, without all parents having a height too.

Try the following:

```css
body, html {
  height: 100%;
  width: 100%;
}

div#map {
  width: 100%;
  height: 100%;
}

```

```html
<div id="map" style="width: 100%; height: 100%;">
	{!! Mapper::render() !!}
</div>
```
